name: Release
permissions:
  contents: write
  pages: write
  id-token: write
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    env:
      environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

